name: Build OpenClash Subscription

on:
  schedule:
    # Каждый вторник 00:00 UTC
    - cron: "0 0 * * 2"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with write token)
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Create dist dir and download country lists (with retries)
        run: |
          mkdir -p dist
          set -e
          curl -fsSL --retry 3 --retry-delay 2 https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Finland.txt -o dist/FI.txt || true
          curl -fsSL --retry 3 --retry-delay 2 https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Sweden.txt -o dist/SE.txt || true
          curl -fsSL --retry 3 --retry-delay 2 https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Estonia.txt -o dist/EE.txt || true
          curl -fsSL --retry 3 --retry-delay 2 https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Lithuania.txt -o dist/LI.txt || true
          curl -fsSL --retry 3 --retry-delay 2 https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Latvia.txt -o dist/LT.txt || true
          curl -fsSL --retry 3 --retry-delay 2 https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Norway.txt -o dist/NO.txt || true

      - name: Show downloaded files (debug)
        run: |
          echo "Files in dist:"
          ls -lah dist || true

      - name: Combine, clean and deduplicate
        run: |
          files=""
          for f in dist/FI.txt dist/SE.txt dist/EE.txt dist/LI.txt dist/LT.txt dist/NO.txt; do
            [ -f "$f" ] && files="$files $f"
          done

          if [ -z "$files" ]; then
            echo "No source files found; creating empty combined.txt"
            : > dist/combined.txt
          else
            cat $files | sed -e 's/\r$//' | sed -n '/\S/p' | awk '!seen[$0]++' > dist/combined.txt
          fi

          echo "Combined lines:" && wc -l dist/combined.txt
          head -n 30 dist/combined.txt || true

      - name: Validate content (must contain protocol URIs)
        run: |
          if grep -E -i '(ss://|vless://|vmess://|trojan://|hysteria://)' dist/combined.txt >/dev/null; then
            echo "OK: protocol URIs present" && echo "1" > dist/has_protocols
          else
            echo "WARN: no protocol URIs found - will NOT update subscription" && rm -f dist/has_protocols || true
          fi

      - name: Encode and prepare output
        run: |
          if [ -f dist/has_protocols ]; then
            base64 -w 0 dist/combined.txt > dist/combined.b64.txt
          else
            echo -n "" > dist/combined.b64.txt
          fi
          ls -lh dist/combined.b64.txt

      - name: Commit and push only if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/combined.b64.txt || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update subscription (FI,SE,EE,LI,LT,NO) [skip ci]" || (echo "commit failed" && exit 1)
          git push || (echo "git push failed — проверь Workflow permissions" && exit 1)
