name: Build OpenClash Subscription

on:
  schedule:
    # Каждый вторник в 00:00 UTC (подставь другое время, см. пояснения ниже)
    - cron: "0 0 * * 2"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download configs from NiREvil/vless
        run: |
          mkdir -p dist
          curl -sL https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Finland.txt -o dist/FI.txt
          curl -sL https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Sweden.txt -o dist/SE.txt
          curl -sL https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Estonia.txt -o dist/EE.txt
          curl -sL https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Lithuania.txt -o dist/LI.txt
          curl -sL https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Latvia.txt -o dist/LT.txt
          curl -sL https://raw.githubusercontent.com/10ium/ScrapeAndCategorize/refs/heads/main/output_configs/Norway.txt -o dist/LT.txt

      - name: Combine configs
        run: |
          cat dist/FI.txt \
              dist/SE.txt \
              dist/EE.txt \
              dist/LI.txt \
              dist/LT.txt > dist/combined.txt

      - name: Convert to base64
        run: |
          base64 -w 0 dist/combined.txt > dist/combined.b64.txt

      - name: Commit and push result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/combined.b64.txt
          git commit -m "Update subscription [skip ci]" || echo "No changes"
          git push
